### ISSUE TITLE
Complete docs for project install

### ISSUE THREAD

**Issue by lfortunier** [smartbooster/symfony-docker#23]
## Goal
Complete docs for project install 

## Steps
- [x] In the existing docker doc : clean remove is not really clean, it's recleimed. ~~Use `docker $ACTION rm` instead~~ add `-a` option to command
- [x] docker permission isssue : `sudo usermod -aG docker $USER` + reboot
- [x] add gitlab ssh key : https://docs.gitlab.com/ee/user/ssh.html
- [x] install make : `sudo apt install make`
- [x] add "How to get the .git history of an installed vendor" doc
- [x] permission in `make install` : Use real user id in Dockerfile

**Comment by mathieu-ducrot** [comment]
@lfortunier for the docker removing part juste add the -a option

**Comment by mathieu-ducrot** [comment]
Debug info about the "permission in make install" step

Error during composer vendor install :
> /app/vendor does not exist and could not be created:

Potential git fix : 
```bash
git config --global --add safe.directory /app
```

**Comment by mathieu-ducrot** [comment]
@lfortunier you can also add the composer.md doc about "How to get the .git history of an installed vendor"
